In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'1.5.0'

### tf.strided_slice

In [5]:
x = tf.placeholder(shape=[None, None], dtype=tf.int32, name="x")
ending = tf.strided_slice(x, [0, 0], # begin at point
                             [3, 3], # end at point
                             [2, 1]) # strides per hop
sess = tf.InteractiveSession()

y = sess.run(ending, feed_dict={
    x: [
        [1, 2, 3],
        [4, 5, 6], 
        [7, 8, 9]
    ]
})

print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
x = tf.placeholder(shape=[None, None, None], dtype=tf.int32, name="x")
ending = tf.strided_slice(x, [0, 1, 0], # begin at point
                             [3, 3, 3], # end at point
                             [1, 1, 1]) # strides per hop
sess = tf.InteractiveSession()

y = sess.run(ending, feed_dict={
    x: [[[1, 1, 1], [2, 2, 2]],
        [[3, 3, 3], [4, 4, 4]],
        [[5, 5, 5], [6, 6, 6]]]
})

print(y)

[[[2 2 2]]

 [[4 4 4]]

 [[6 6 6]]]


##### References
- https://www.tensorflow.org/api_docs/python/tf/strided_slice
- https://medium.com/@mozesr/python-matrix-strides-numpy-tensorflow-5f73f6fa1aca
